# Generated by Django 6.1.1 on 2026-09-13 20:49

import compiler.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('over_limit', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, upload_to=compiler.models.resume_upload_path)),
                ('tex_file', models.FileField(blank=True, upload_to=compiler.models.resume_upload_path)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='presets.resumepreset')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
