# Generated by Django 6.1.1 on 2026-09-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template', models.CharField(choices=[('jakes', "Jake's Resume")], default='jakes', max_length=20)),
                ('include_gpa', models.BooleanField(default=True)),
                ('include_coursework', models.BooleanField(default=True)),
                ('page_limit', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PresetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.component')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_components', to='presets.resumepreset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PresetBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('bullet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bullet')),
                ('preset_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_bullets', to='presets.presetcomponent')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('preset_component', 'bullet'), name='unique_bullet_per_preset_component')],
            },
        ),
        migrations.CreateModel(
            name='PresetSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.skill')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_skills', to='presets.resumepreset')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'skill'), name='unique_skill_per_preset')],
            },
        ),
        migrations.AddConstraint(
            model_name='presetcomponent',
            constraint=models.UniqueConstraint(fields=('preset', 'component'), name='unique_component_per_preset'),
        ),
    ]
