# Generated by Django 6.1.1 on 2026-09-14 04:12, then hand-ordered so the
# data step runs while both the old flag and the new table exist.

import django.db.models.deletion
from django.db import migrations, models


def seed_from_flag(apps, schema_editor):
    """Presets that had include_coursework=True keep rendering every course."""
    ResumePreset = apps.get_model('presets', 'ResumePreset')
    PresetCoursework = apps.get_model('presets', 'PresetCoursework')
    Coursework = apps.get_model('bank', 'Coursework')
    courses = list(Coursework.objects.all())
    PresetCoursework.objects.bulk_create([
        PresetCoursework(preset=preset, coursework=course, order=course.order)
        for preset in ResumePreset.objects.filter(include_coursework=True)
        for course in courses
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetCoursework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.coursework')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_coursework', to='presets.resumepreset')),
            ],
            options={
                'verbose_name_plural': 'preset coursework',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'coursework'), name='unique_coursework_per_preset')],
            },
        ),
        migrations.RunPython(seed_from_flag, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='resumepreset',
            name='include_coursework',
        ),
    ]
